modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "createutilities"
version = "0.1"
displayName = "Create Utilities"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/create-utilities"
logoFile = "logo.png"
authors = "FallenReaper"
description = '''
Aims to expand the Create Mod by introducing new tools and additions!
'''
[[dependencies.createutilities]]
modId="forge"
mandatory=true
versionRange="[43.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.createutilities]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.createutilities]]
modId = "create"
mandatory = true
versionRange = "[mc1.18.2_v0.5.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createutilities]]
modId="flywheel"
mandatory=true
versionRange="[0.6.8,0.6.9)"
ordering="AFTER"
side="CLIENT"